#!/bin/bash
clear
printf '\n· Minecraft Installer\n· Version: 0.1\n· Author: KanuX-14\n· Date: 02/02/2021\n· Time: 1:34 PM\n\n'
sleep 1
mkdir -p ./.temp_download
mkdir -p $HOME/Desktop
wget https://launcher.mojang.com/download/Minecraft.deb -O ./.temp_download/Minecraft.deb
printf '\nYou need to give the password in order to install the Minecraft.\n\n'
sudo dpkg -i ./.temp_download/Minecraft.deb
sudo apt --fix-broken install -y
rm -rf ./.temp_download
printf '[Desktop Entry]\nType=Application\nVersion=1.0\nName=Minecraft Launcher\nComment=Official Minecraft Launcher\nExec=/opt/minecraft-launcher/minecraft-launcher\nPath=/opt/minecraft-launcher\nIcon=minecraft-launcher\nTerminal=false\nCategories=Game;Application;' > $HOME/Desktop/minecraft-launcher.desktop
printf '\nDone! You can now play Minecraft!\n'
sleep 0.3
printf 'Run Minecraft now? [Y/n]\n'
read answer
case $answer in
  Y|y) minecraft-launcher ;;
  N|n) exit ;;
  *) minecraft-launcher ;;
esac

